# ワークフローの名前
name: GCP Authentication Debug

# mainブランチへのプッシュで実行
on:
  push:
    branches:
      - main

jobs:
  # 'debug-gcp-auth'という名前のジョブ
  debug-gcp-auth:
    # 実行環境
    runs-on: ubuntu-latest
    # 認証に必要な権限
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. GCPへの認証（ここまでは本番と同じ）
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      # 3. gcloudコマンドラインツールをセットアップ
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 4. ★★★ 認証状態の確認 ★★★
      # このステップが成功するかどうかが重要
      - name: Check GCP Auth Status
        run: |
          echo "--- Checking active gcloud account ---"
          gcloud auth list
          echo "------------------------------------"
          echo "--- Checking application default credentials ---"
          gcloud auth application-default print-access-token
