name: Deploy Corporate Site to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # pnpmをインストールし、キャッシュを有効にする
      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          pnpm-version: "latest" # または '9' などバージョン指定も可
          cache: "pnpm"

      # pnpm install を実行
      - name: Install dependencies
        run: pnpm install

      # pnpm run build を実行
      - name: Build Astro site
        run: pnpm run build

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Deploy to Cloud Storage
        run: |
          gcloud storage rsync ./dist gs://keiyousha --recursive --delete-unmatched-destination-objects
