name: Deploy Corporate Site to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro site
        run: pnpm run build

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Deploy to Cloud Storage
        run: |
          gcloud storage rsync ./dist gs://keiyousha --recursive --delete-unmatched-destination-objects

      # HTMLファイル: 常に最新のものを表示させるため、キャッシュしない（毎回サーバーに確認）
      # Astroが生成するハッシュ付きのCSS/JSアセット: 1年間キャッシュし、不変（immutable）とマーク
      # その他の画像やフォントファイル: 1年間キャッシュ
      - name: Set Cache-Control headers
        run: |
          echo "Setting Cache-Control headers..."
          gcloud storage objects update gs://keiyousha/**/*.html --cache-control="no-cache"
          gcloud storage objects update gs://keiyousha/_astro/** --cache-control="public, max-age=31536000, immutable"
          gcloud storage objects update gs://keiyousha/**/*.{css,js,png,jpg,jpeg,gif,svg,ico,webp,woff,woff2} -r --cache-control="public, max-age=31536000, immutable"
          echo "Cache-Control headers set successfully."
